---
version: "3.9"

x-common-variables: &common-variables
  POSTGRES_DB: postgres
  POSTGRES_USER: odoo
  POSTGRES_PORT: 5432
  POSTGRES_PASSWORD: odoo

services:
  odoo:
    build:
      context: .
    environment:
      <<: *common-variables
      ODOO_OPT_STOP_AFTER_INIT: ""
      ODOO_OPT_TEST_ENABLE: ""
      ODOO_INIT_SCOPE_PATHS: /opt/odoo/projects/oerp-odoo
      ODOO_OPT_TEST_TAGS: >-
        -base,-web,-crm,-sale,-sale_stock,-salec_crm,-account,-stock_account,-account_invoice_extract,-account_edi_facturx,-payment,-stock,-project,-repair,-product,-hr_org_chart
    depends_on:
      - db
    volumes:
      - odoo-filestore:/opt/odoo/data
    networks:
      - backend
  db:
    image: postgres:13
    environment: *common-variables
    networks:
      - backend

volumes:
  odoo-filestore:
    driver: local

networks:
  backend:
