---
name: Statuses
# yamllint disable-line rule:truthy
on:
  push:
    branches-ignore: ["15.0"]
jobs:
  test:
    name: Odoo Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: login to docker hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u \
          "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Run and Test Odoo
        run: |
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit
